Update geom-text.r
tidyverse/ggplot2 pull request #4389
Opened 2021-03-25 16:12 UTC by larspijnappel

As proposed, here's a PR for the documentation improvement regarding the unsupported `check_overlap` argument for `geom_label()` (#4331).

Note: this request replaces the previous PR #4332 as it can't be completed due to loss of the previous fork.

2021-03-26 12:39 UTC, thomasp85 commented
Can I get you to run roxygen to also update the docs

2021-03-26 17:42 UTC, larspijnappel commented
No problem, although that would be another first time for me as well :-)

So, in my local branch I performed `devtools::document()` and the `man\geom_text.Rd` has been updated successfully. 

Do I just `pr_push()` again to complete all of it?

2021-04-08 08:42 UTC, thomasp85 commented
Yes - every change can be added to the PR using `pr_push()`

2021-04-09 06:53 UTC, thomasp85 requested changes

2021-04-09 06:53 UTC, thomasp85 commented on NAMESPACE
> +export(scale_color_gray)
Can I get you to remove the two new exports in the NAMESPACE... It is not your fault, but another PR did not get oxygenised and this is now causing your PR to fail check. Removing these lets us handle it in a different PR

2021-04-09 06:53 UTC, thomasp85 commented on NAMESPACE
> +export(scale_fill_gray)
same as above

2021-04-09 09:21 UTC, thomasp85 approved these changes
Thanks!

2021-04-09 09:21 UTC, merged