Allow `scale_{x/y}_sqrt()` to have breaks at 0.
tidyverse/ggplot2 pull request #4775
Opened 2022-03-24 20:20 UTC by teunbrand

Apologies for submitting a PR that will not work (yet). It aims to fix #980.

In anticipation of https://github.com/r-lib/scales/pull/336, this PR implements (a version of) the fix suggested [here](https://github.com/tidyverse/ggplot2/issues/980#issuecomment-505455353) that has become viable thanks to the change in {scales}. 

Note that this PR will likely not pass the automated checks until the new {scales} version hits CRAN, at which point is seems a good idea to bump the required version in the description file.

2022-04-14 20:45 UTC, teunbrand commented
With the release of the new {scales} version, this PR is now ready for your perusal. The failing check appears, to my untrained eyes, unrelated to the code in this PR.

2022-04-19 09:41 UTC, thomasp85 commented
Can I get you to add a NEWS bullet?

2022-04-19 17:34 UTC, teunbrand commented
Of course, apologies for not including it in the first place!

2022-04-19 20:26 UTC, hadley requested changes
Looks good, but I think it needs an explicit test, rather than just relying on a change to an existing visual test.

2022-04-19 20:26 UTC, hadley commented on NEWS.md
> +
Could you please remove this spurious diff?

2022-05-17 07:26 UTC, merged