Nicer error message in coord-cartesian
tidyverse/ggplot2 pull request #4894
Opened 2022-06-29 23:26 UTC by 92amartins

This is an attempt to fix https://github.com/tidyverse/ggplot2/issues/4601

2022-07-05 11:51 UTC, thomasp85 commented on R/coord-cartesian-.r
> +
```suggestion
  if (is.environment(xlim)) {
    cli::cli_abort("Did you mean {.code xlim = c(...)}?")
  }
  if (is.environment(ylim)) {
    cli::cli_abort('Did you mean {.code ylim = c(...)}?')
  }
```

2022-07-05 11:53 UTC, thomasp85 requested changes
Thanks. Can I get you to update to match the style guide (suggested change), as well as add a unit test for the two errors

2022-07-08 00:09 UTC, 92amartins commented
> Thanks. Can I get you to update to match the style guide (suggested change), as well as add a unit test for the two errors

Thanks, for the review @thomasp85!

I applied your suggestion regarding style in f047b04a0a99adbb00eb47d803d87e4e0a856f43

And wrote a unit test for the arguments in eec525e380f3a2a39c65662307afb44b7eb3b132

Please let me know if further improvements are needed.

2023-02-15 21:01 UTC, 92amartins commented
Good point, @teunbrand! I'll extend the checks for other functions in the coord family.

2023-04-17 16:46 UTC, teunbrand commented
If you intend to recycle the checks in other `coord_*()` functions, it might be worth it to write a check function for coord limits. Here is a rough draft for one:

``` r
library(rlang)

check_coord_limits <- function(
  limits, arg = caller_arg(limits), call = caller_env()
) {
  if (is.null(limits)) {
    return(invisible(NULL))
  }
  if (!is.vector(limits) || length(limits) != 2) {
    what <- "{.obj_type_friendly {limits}}"
    if (is.vector(limits)) {
      what <- paste0(what, " of length {length(limits)}")
    }
    cli::cli_abort(
      paste0("{.arg {arg}} must be a vector of length 2, not ", what, "."),
      call = call
    )
  }
  invisible()
}

# Erroneous input
xlim <- ggplot2::xlim(0, 2)
ylim <- 1:3

check_coord_limits(xlim)
#> Error:
#> ! `xlim` must be a vector of length 2, not a
#>   <ScaleContinuousPosition/ScaleContinuous/Scale/ggproto/gg> object.
#> Backtrace:
#>     ▆
#>  1. └─global check_coord_limits(xlim)
#>  2.   └─cli::cli_abort(...)
#>  3.     └─rlang::abort(...)
check_coord_limits(ylim)
#> Error:
#> ! `ylim` must be a vector of length 2, not an integer vector of length
#>   3.
#> Backtrace:
#>     ▆
#>  1. └─global check_coord_limits(ylim)
#>  2.   └─cli::cli_abort(...)
#>  3.     └─rlang::abort(...)
```

<sup>Created on 2023-04-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2023-05-05 18:36 UTC, teunbrand commented
As pointed out in #5297, the lengthy check I proposed earlier might be better replaced by `vec_check_size(xlim, 2)`.

2023-06-13 20:19 UTC, teunbrand approved these changes
Thanks for doing this: this looks good to me.

2023-06-23 08:12 UTC, thomasp85 approved these changes
LGTM

2023-06-23 19:50 UTC, teunbrand commented
Thanks so much @92amartins for incorporating the commentary and for the PR!

2023-06-23 19:50 UTC, merged