Revert renaming `Scale$trans` to `Scale$transformation`
tidyverse/ggplot2 pull request #5626
Opened 2024-01-04 08:40 UTC by teunbrand

This PR to the RC aims to fix some reverse dependency problems.

To briefly describe the problem: people are using foo <- Scale$trans all over their code. We have removed the Scale$trans field in https://github.com/tidyverse/ggplot2/pull/5566, in favour of the Scale$transformation field, which broke all that code. This PR reverses the renaming of the field specifically.

I think the `Scale$get_transformation()` getter is still useful, so I left it in. It is mostly useful for view scales where the transformation is hidden in the `ViewScale$scale$trans`.

2024-01-05 10:01 UTC, teunbrand commented
TODO: use `get_transformation()` consistently

2024-01-05 20:18 UTC, thomasp85 commented
I think you need to start from scratch because you've confused yourself about what to rename where. There is a method `transform()` which is not touched and you shouldn't try to rename the. 

I think basically it is only the field that should be renamed, the `get_transformation()` method should be updated for that and that would be it

2024-01-05 20:19 UTC, thomasp85 requested changes
See previous comment

2024-01-05 21:16 UTC, teunbrand commented
I'm not sure I'm following along here. The following bit has me confused:

> There is a method transform() which is not touched and you shouldn't try to rename the.

I am not touching the `Scale$transform()` method in this PR, just the secondary axis' `transform` field, which recieves the user-provided transformation function. Perhaps the confusing thing is that in #5566 I renamed the secondary axis field to `transform` instead of `transformation`?

2024-01-08 13:31 UTC, thomasp85 commented on R/stat-function.R
> +      y_out <- scales$y$transform(y_out)
This seems wrong still - rest is ok

2024-01-08 13:54 UTC, thomasp85 approved these changes
LGTM

2024-01-08 13:57 UTC, teunbrand commented
Thanks for the reviews Thomas!

2024-01-08 13:57 UTC, merged