check type for date_breaks and date_minor_breaks
tidyverse/ggplot2 pull request #6044
Opened 2024-08-15 20:47 UTC by RodDalBen

check type for date_breaks and date_minor_breaks #5880

2024-08-15 21:29 UTC, thomasp85 requested changes
Thank you! Can I get you to add two unit tests that checks for the correct behaviour on these cases

2024-09-10 08:06 UTC, teunbrand commented
Added check for `date_label` too and tests.

2024-11-11 09:39 UTC, thomasp85 reviewed
@teunbrand can you update the tests to use snapshots and then finish it off

2024-11-11 09:39 UTC, thomasp85 approved these changes

2024-11-11 11:35 UTC, merged