Fix bug in `guide_axis_logticks(negative.small)`
tidyverse/ggplot2 pull request #6126
Opened 2024-09-30 08:42 UTC by teunbrand

This PR aims to fix #6121.

Briefly, is ensures that the limits it uses to calculate log-breaks are sorted.
Moreover, it picks a better default value for `negative.small` when the scale maximum is small.

Some examples based on the issue's regex; first showing that it now doesn't error and doesn't render absurd tick marks:

``` r
devtools::load_all("~/packages/ggplot2")
#> ℹ Loading ggplot2

p <- data.frame(
  "Y_val" = c(0, 1e-6, 1e-5, 1e-4),
  "X_val" = c(10, 20, 30, 40)
) |>
  ggplot(aes(x = X_val, y = Y_val)) + 
  geom_point() +
  scale_y_continuous(transform = pseudo_log_trans(sigma = 1e-7, base = 10))

p + guides(y = "axis_logticks")
```

![](https://i.imgur.com/bgkbsqV.png)

Second, showing the plot with a reasonable `negative.small` argument for this plot:

``` r
p + guides(y = guide_axis_logticks(negative.small = 1e-7))
```

![](https://i.imgur.com/0qYA7jx.png)

Lastly, showing the plot with an inappropriate `negative.small` argument (which still doesn't throw an error).

``` r
p + guides(y = guide_axis_logticks(negative.small = 1))
```

![](https://i.imgur.com/jjhb5Ya.png)

<sup>Created on 2024-09-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

2024-10-29 09:48 UTC, teunbrand commented
Let's wait on {scales}  to release a new version so we can  use https://github.com/r-lib/scales/pull/452 for this

2025-05-19 07:22 UTC, thomasp85 requested changes

2025-05-19 07:22 UTC, thomasp85 commented on R/guide-axis-logticks.R
> +      ones  <- ones[ones >= small]
Actually, I'd rather you define `small <- NULL` and then in the first `has_negative` block you set it to something. Then in this block, instead of testing `has_negative` you test `!is.null(small)`

2025-05-19 07:27 UTC, teunbrand commented on R/guide-axis-logticks.R
> +      ones  <- ones[ones >= small]
This part of the code that we're commenting on is outdated. It has mostly been replaced by `scales::minor_breaks_log`.

2025-05-20 08:37 UTC, thomasp85 approved these changes
LGTM

2025-05-20 09:02 UTC, merged