Flexible palettes
tidyverse/ggplot2 pull request #6216
Opened 2024-12-04 15:32 UTC by teunbrand

This PR aims to fix #6064 and replaces #6112.

Briefly, it attempts to cast non-null `palette` arguments with `as_discrete_pal()`/`as_continuous_pal()`. These are currently shims.

This PR replaces the older one because I could implemented more cleanly now that #5946 is merged.

2025-01-22 14:31 UTC, teunbrand commented
Includes fix for #6289, since it'd touch the same code.

2025-02-27 08:55 UTC, thomasp85 requested changes
I know the proposed changes don't practically affect the evaluation but I prefer to collect logical tests that define a specific condition (if that makes sense)

2025-02-27 08:55 UTC, thomasp85 commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
```suggestion
  if (has_old_args || (!is.null(type) && is.null(palette))) {
```

2025-02-27 08:55 UTC, thomasp85 commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
```suggestion
  if (has_old_args || (!is.null(type) && is.null(palette))) {
```

2025-02-27 08:55 UTC, thomasp85 commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
```suggestion
  if (has_old_args || (!is.null(type) && is.null(palette))) {
```

2025-02-27 08:55 UTC, thomasp85 commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
```suggestion
  if (has_old_args || (!is.null(type) && is.null(palette))) {
```

2025-03-25 08:08 UTC, thomasp85 commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
I know I'm being pedantic here but please make the same changes to the logic tests here and below :-)

2025-03-25 08:18 UTC, teunbrand commented on R/scale-colour.R
> +  if (has_old_args || !is.null(type) && is.null(palette)) {
Ah my bad, I should've spotted these!

2025-03-25 10:24 UTC, thomasp85 approved these changes
LGTM

2025-03-25 14:43 UTC, merged