Explain how to fix fill guide for points with filled shapes
tidyverse/ggplot2 pull request #6229
Opened 2024-12-10 22:46 UTC by arcresu

Adds an example for `geom_point` and a small note to the relevant part of the specs vignette so there's a better chance of people finding out how to deal with guides for filled shapes. Closes #6177.

2024-12-12 08:11 UTC, teunbrand requested changes
Thank your for the PR! I don't mean to be annoying, but I have a some nitpicks I'd like to see altered, see comments.

2024-12-12 08:11 UTC, teunbrand commented on R/geom-point.R
> +#' ggplot(mtcars, aes(wt, mpg, fill = factor(carb), shape = factor(cyl), colour = factor(vs))) +
```suggestion
#' ggplot(mtcars, aes(wt, mpg, fill = factor(carb), shape = factor(cyl))) +
```
Colour mapping is distracting from the point this example illustrates

2024-12-12 08:11 UTC, teunbrand commented on R/geom-point.R
> +#' # override it in the guide in order to see the fill reflected in the legend
```suggestion
#' # The default shape in legends is not filled, but you can
#' # override the shape in the guide to reflect the fill
```
Just slightly more terse

2024-12-12 08:11 UTC, teunbrand commented on vignettes/ggplot2-specs.Rmd
> +
I don't think the first sentence clarifies anything.
I think it'd be better to just name the most common situation wherein the shape needs to be overriden, namely when you use a shape mapping with a discrete fill.

2024-12-13 04:45 UTC, arcresu commented
Thanks for the suggestions!

My thinking with the "advanced feature" warning was just to let people know that some code might assume points are not filled. Documenting that expectation probably would have stopped me from raising this in the first place. I rephrased that sentence; hopefully it's better now.

2024-12-13 08:02 UTC, teunbrand approved these changes
Looks great, thank you for the contribution!

2024-12-13 08:02 UTC, merged